compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
machine_rank: 0
main_process_ip: 127.0.0.1
main_process_port: 29500
num_machines: 1
num_processes: 4
mixed_precision: bf16
use_cpu: false
